config:
  domain: <my-domain>  # domain to retrieve a cert for (passed to ACME servers, required)
  email: <my-email>  # email for acme auth (passed to ACME servers, required)
  port: 80  # local port for acme domain check (should be 80, change if running behind a proxy)

  output: ./data  # dir to store the keys and certs (for internal use)

  staging: False  # generate staging certs

  # rfc3161 timestamp authority cert chain + timestamp urls
  # at least one required, if multiple, one is selected at random
  timestamping:
    - certfile: ./ts-certs/ts-chain.pem # time server cert chain (cert + ca cert)
      url: http://freetsa.org/tsr  # timeserver URL
